// cspell: disable
export const COUNTRIES = [
  { id: "af", countryName: "Afghanistan (‫افغانستان‬‎)", dialCode: "+93" },
  { id: "al", countryName: "Albania (Shqipëri)", dialCode: "+355" },
  { id: "dz", countryName: "Algeria (‫الجزائر‬‎)", dialCode: "+213" },
  { id: "as", countryName: "American Samoa", dialCode: "+1684" },
  { id: "ad", countryName: "Andorra", dialCode: "+376" },
  { id: "ao", countryName: "Angola", dialCode: "+244" },
  { id: "ai", countryName: "Anguilla", dialCode: "+1264" },
  { id: "ag", countryName: "Antigua and Barbuda", dialCode: "+1268" },
  { id: "ar", countryName: "Argentina", dialCode: "+54" },
  { id: "am", countryName: "Armenia (Հայաստան)", dialCode: "+374" },
  { id: "aw", countryName: "Aruba", dialCode: "+297" },
  { id: "au", countryName: "Australia", dialCode: "+61" },
  { id: "at", countryName: "Austria (Österreich)", dialCode: "+43" },
  { id: "az", countryName: "Azerbaijan (Azərbaycan)", dialCode: "+994" },
  { id: "bs", countryName: "Bahamas", dialCode: "+1242" },
  { id: "bh", countryName: "Bahrain (‫البحرين‬‎)", dialCode: "+973" },
  { id: "bd", countryName: "Bangladesh (বাংলাদেশ)", dialCode: "+880" },
  { id: "bb", countryName: "Barbados", dialCode: "+1246" },
  { id: "by", countryName: "Belarus (Беларусь)", dialCode: "+375" },
  { id: "be", countryName: "Belgium (België)", dialCode: "+32" },
  { id: "bz", countryName: "Belize", dialCode: "+501" },
  { id: "bj", countryName: "Benin (Bénin)", dialCode: "+229" },
  { id: "bm", countryName: "Bermuda", dialCode: "+1441" },
  { id: "bt", countryName: "Bhutan (འབྲུག)", dialCode: "+975" },
  { id: "bo", countryName: "Bolivia", dialCode: "+591" },
  {
    id: "ba",
    countryName: "Bosnia and Herzegovina (Босна и Херцеговина)",
    dialCode: "+387",
  },
  { id: "bw", countryName: "Botswana", dialCode: "+267" },
  { id: "br", countryName: "Brazil (Brasil)", dialCode: "+55" },
  { id: "io", countryName: "British Indian Ocean Territory", dialCode: "+246" },
  { id: "vg", countryName: "British Virgin Islands", dialCode: "+1284" },
  { id: "bn", countryName: "Brunei", dialCode: "+673" },
  { id: "bg", countryName: "Bulgaria (България)", dialCode: "+359" },
  { id: "bf", countryName: "Burkina Faso", dialCode: "+226" },
  { id: "bi", countryName: "Burundi (Uburundi)", dialCode: "+257" },
  { id: "kh", countryName: "Cambodia (កម្ពុជា)", dialCode: "+855" },
  { id: "cm", countryName: "Cameroon (Cameroun)", dialCode: "+237" },
  { id: "ca", countryName: "Canada", dialCode: "+1" },
  { id: "cv", countryName: "Cape Verde (Kabu Verdi)", dialCode: "+238" },
  { id: "ky", countryName: "Cayman Islands", dialCode: "+1345" },
  {
    id: "cf",
    countryName: "Central African Republic (République centrafricaine)",
    dialCode: "+236",
  },
  { id: "td", countryName: "Chad (Tchad)", dialCode: "+235" },
  { id: "cl", countryName: "Chile", dialCode: "+56" },
  { id: "cn", countryName: "China (中国)", dialCode: "+86" },
  { id: "cx", countryName: "Christmas Island", dialCode: "+61" },
  { id: "cc", countryName: "Cocos (Keeling) Islands", dialCode: "+61" },
  { id: "co", countryName: "Colombia", dialCode: "+57" },
  { id: "km", countryName: "Comoros (‫جزر القمر‬‎)", dialCode: "+269" },
  {
    id: "cd",
    countryName: "Congo (DRC) (Jamhuri ya Kisoemokrasia ya Kongo)",
    dialCode: "+243",
  },
  {
    id: "cg",
    countryName: "Congo (Republic) (Congo-Brazzaville)",
    dialCode: "+242",
  },
  { id: "ck", countryName: "Cook Islands", dialCode: "+682" },
  { id: "cr", countryName: "Costa Rica", dialCode: "+506" },
  { id: "ci", countryName: "Côte d’Ivoire", dialCode: "+225" },
  { id: "hr", countryName: "Croatia (Hrvatska)", dialCode: "+385" },
  { id: "cu", countryName: "Cuba", dialCode: "+53" },
  { id: "cw", countryName: "Curaçao", dialCode: "+599" },
  { id: "cy", countryName: "Cyprus (Κύπρος)", dialCode: "+357" },
  {
    id: "cz",
    countryName: "Czech Republic (Česká republika)",
    dialCode: "+420",
  },
  { id: "dk", countryName: "Denmark (Danmark)", dialCode: "+45" },
  { id: "dj", countryName: "Djibouti", dialCode: "+253" },
  { id: "dm", countryName: "Dominica", dialCode: "+1767" },
  {
    id: "do",
    countryName: "Dominican Republic (República Dominicana)",
    dialCode: "+1",
  },
  { id: "ec", countryName: "Ecuador", dialCode: "+593" },
  { id: "eg", countryName: "Egypt (‫مصر‬‎)", dialCode: "+20" },
  { id: "sv", countryName: "El Salvador", dialCode: "+503" },
  {
    id: "gq",
    countryName: "Equatorial Guinea (Guinea Ecuatorial)",
    dialCode: "+240",
  },
  { id: "er", countryName: "Eritrea", dialCode: "+291" },
  { id: "ee", countryName: "Estonia (Eesti)", dialCode: "+372" },
  { id: "et", countryName: "Ethiopia", dialCode: "+251" },
  {
    id: "fk",
    countryName: "Falkland Islands (Islas Malvinas)",
    dialCode: "+500",
  },
  { id: "fo", countryName: "Faroe Islands (Føroyar)", dialCode: "+298" },
  { id: "fj", countryName: "Fiji", dialCode: "+679" },
  { id: "fi", countryName: "Finland (Suomi)", dialCode: "+358" },
  { id: "fr", countryName: "France", dialCode: "+33" },
  {
    id: "gf",
    countryName: "French Guiana (Guyane française)",
    dialCode: "+594",
  },
  {
    id: "pf",
    countryName: "French Polynesia (Polynésie française)",
    dialCode: "+689",
  },
  { id: "ga", countryName: "Gabon", dialCode: "+241" },
  { id: "gm", countryName: "Gambia", dialCode: "+220" },
  { id: "ge", countryName: "Georgia (საქართველო)", dialCode: "+995" },
  { id: "de", countryName: "Germany (Deutschland)", dialCode: "+49" },
  { id: "gh", countryName: "Ghana (Gaana)", dialCode: "+233" },
  { id: "gi", countryName: "Gibraltar", dialCode: "+350" },
  { id: "gr", countryName: "Greece (Ελλάδα)", dialCode: "+30" },
  { id: "gl", countryName: "Greenland (Kalaallit Nunaat)", dialCode: "+299" },
  { id: "gd", countryName: "Grenada", dialCode: "+1473" },
  { id: "gp", countryName: "Guadeloupe", dialCode: "+590" },
  { id: "gu", countryName: "Guam", dialCode: "+1671" },
  { id: "gt", countryName: "Guatemala", dialCode: "+502" },
  { id: "gg", countryName: "Guernsey", dialCode: "+44" },
  { id: "gn", countryName: "Guinea (Guinée)", dialCode: "+224" },
  { id: "gw", countryName: "Guinea-Bissau (Guiné Bissau)", dialCode: "+245" },
  { id: "gy", countryName: "Guyana", dialCode: "+592" },
  { id: "ht", countryName: "Haiti", dialCode: "+509" },
  { id: "hn", countryName: "Honduras", dialCode: "+504" },
  { id: "hk", countryName: "Hong Kong (香港)", dialCode: "+852" },
  { id: "hu", countryName: "Hungary (Magyarország)", dialCode: "+36" },
  { id: "is", countryName: "Iceland (Ísland)", dialCode: "+354" },
  { id: "in", countryName: "India (भारत)", dialCode: "+91" },
  { id: "id", countryName: "Indonesia", dialCode: "+62" },
  { id: "ir", countryName: "Iran (‫ایران‬‎)", dialCode: "+98" },
  { id: "iq", countryName: "Iraq (‫العراق‬‎)", dialCode: "+964" },
  { id: "ie", countryName: "Ireland", dialCode: "+353" },
  { id: "im", countryName: "Isle of Man", dialCode: "+44" },
  { id: "il", countryName: "Israel (‫ישראל‬‎)", dialCode: "+972" },
  { id: "it", countryName: "Italy (Italia)", dialCode: "+39" },
  { id: "jm", countryName: "Jamaica", dialCode: "+1" },
  { id: "jp", countryName: "Japan (日本)", dialCode: "+81" },
  { id: "je", countryName: "Jersey", dialCode: "+44" },
  { id: "jo", countryName: "Jordan (‫الأردن‬‎)", dialCode: "+962" },
  { id: "kz", countryName: "Kazakhstan (Казахстан)", dialCode: "+7" },
  { id: "ke", countryName: "Kenya", dialCode: "+254" },
  { id: "ki", countryName: "Kiribati", dialCode: "+686" },
  { id: "xk", countryName: "Kosovo", dialCode: "+383" },
  { id: "kw", countryName: "Kuwait (‫الكويت‬‎)", dialCode: "+965" },
  { id: "kg", countryName: "Kyrgyzstan (Кыргызстан)", dialCode: "+996" },
  { id: "la", countryName: "Laos (ລາວ)", dialCode: "+856" },
  { id: "lv", countryName: "Latvia (Latvija)", dialCode: "+371" },
  { id: "lb", countryName: "Lebanon (‫لبنان‬‎)", dialCode: "+961" },
  { id: "ls", countryName: "Lesotho", dialCode: "+266" },
  { id: "lr", countryName: "Liberia", dialCode: "+231" },
  { id: "ly", countryName: "Libya (‫ليبيا‬‎)", dialCode: "+218" },
  { id: "li", countryName: "Liechtenstein", dialCode: "+423" },
  { id: "lt", countryName: "Lithuania (Lietuva)", dialCode: "+370" },
  { id: "lu", countryName: "Luxembourg", dialCode: "+352" },
  { id: "mo", countryName: "Macau (澳門)", dialCode: "+853" },
  {
    id: "mk",
    countryName: "North Macedonia (FYROM) (Македонија)",
    dialCode: "+389",
  },
  { id: "mg", countryName: "Madagascar (Madagasikara)", dialCode: "+261" },
  { id: "mw", countryName: "Malawi", dialCode: "+265" },
  { id: "my", countryName: "Malaysia", dialCode: "+60" },
  { id: "mv", countryName: "Maldives", dialCode: "+960" },
  { id: "ml", countryName: "Mali", dialCode: "+223" },
  { id: "mt", countryName: "Malta", dialCode: "+356" },
  { id: "mh", countryName: "Marshall Islands", dialCode: "+692" },
  { id: "mq", countryName: "Martinique", dialCode: "+596" },
  { id: "mr", countryName: "Mauritania (‫موريتانيا‬‎)", dialCode: "+222" },
  { id: "mu", countryName: "Mauritius (Moris)", dialCode: "+230" },
  { id: "yt", countryName: "Mayotte", dialCode: "+262" },
  { id: "mx", countryName: "Mexico (México)", dialCode: "+52" },
  { id: "fm", countryName: "Micronesia", dialCode: "+691" },
  { id: "md", countryName: "Moldova (Republica Moldova)", dialCode: "+373" },
  { id: "mc", countryName: "Monaco", dialCode: "+377" },
  { id: "mn", countryName: "Mongolia (Монгол)", dialCode: "+976" },
  { id: "me", countryName: "Montenegro (Crna Gora)", dialCode: "+382" },
  { id: "ms", countryName: "Montserrat", dialCode: "+1664" },
  { id: "ma", countryName: "Morocco (‫المغرب‬‎)", dialCode: "+212" },
  { id: "mz", countryName: "Mozambique (Moçambique)", dialCode: "+258" },
  { id: "mm", countryName: "Myanmar (Burma) (မြန်မာ)", dialCode: "+95" },
  { id: "na", countryName: "Namibia (Namibië)", dialCode: "+264" },
  { id: "nr", countryName: "Nauru", dialCode: "+674" },
  { id: "np", countryName: "Nepal (नेपाल)", dialCode: "+977" },
  { id: "nl", countryName: "Netherlands (Nederland)", dialCode: "+31" },
  {
    id: "nc",
    countryName: "New Caledonia (Nouvelle-Calédonie)",
    dialCode: "+687",
  },
  { id: "nz", countryName: "New Zealand", dialCode: "+64" },
  { id: "ni", countryName: "Nicaragua", dialCode: "+505" },
  { id: "ne", countryName: "Niger (Nijar)", dialCode: "+227" },
  { id: "ng", countryName: "Nigeria", dialCode: "+234" },
  { id: "nu", countryName: "Niue", dialCode: "+683" },
  { id: "nf", countryName: "Norfolk Island", dialCode: "+672" },
  {
    id: "kp",
    countryName: "North Korea (조선 민주주의 인민 공화국)",
    dialCode: "+850",
  },
  { id: "mp", countryName: "Northern Mariana Islands", dialCode: "+1670" },
  { id: "no", countryName: "Norway (Norge)", dialCode: "+47" },
  { id: "om", countryName: "Oman (‫عُمان‬‎)", dialCode: "+968" },
  { id: "pk", countryName: "Pakistan (‫پاکستان‬‎)", dialCode: "+92" },
  { id: "pw", countryName: "Palau", dialCode: "+680" },
  { id: "ps", countryName: "Palestine (‫فلسطين‬‎)", dialCode: "+970" },
  { id: "pa", countryName: "Panama (Panamá)", dialCode: "+507" },
  { id: "pg", countryName: "Papua New Guinea", dialCode: "+675" },
  { id: "py", countryName: "Paraguay", dialCode: "+595" },
  { id: "pe", countryName: "Peru (Perú)", dialCode: "+51" },
  { id: "ph", countryName: "Philippines", dialCode: "+63" },
  { id: "pl", countryName: "Poland (Polska)", dialCode: "+48" },
  { id: "pt", countryName: "Portugal", dialCode: "+351" },
  { id: "pr", countryName: "Puerto Rico", dialCode: "+1" },
  { id: "qa", countryName: "Qatar (‫قطر‬‎)", dialCode: "+974" },
  { id: "re", countryName: "Réunion (La Réunion)", dialCode: "+262" },
  { id: "ro", countryName: "Romania (România)", dialCode: "+40" },
  { id: "ru", countryName: "Russia (Россия)", dialCode: "+7" },
  { id: "rw", countryName: "Rwanda", dialCode: "+250" },
  { id: "bl", countryName: "Saint Barthélemy", dialCode: "+590" },
  { id: "sh", countryName: "Saint Helena", dialCode: "+290" },
  { id: "kn", countryName: "Saint Kitts and Nevis", dialCode: "+1869" },
  { id: "lc", countryName: "Saint Lucia", dialCode: "+1758" },
  {
    id: "mf",
    countryName: "Saint Martin (Saint-Martin (partie française))",
    dialCode: "+590",
  },
  {
    id: "pm",
    countryName: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    dialCode: "+508",
  },
  {
    id: "vc",
    countryName: "Saint Vincent and the Grenadines",
    dialCode: "+1784",
  },
  { id: "ws", countryName: "Samoa", dialCode: "+685" },
  { id: "SM", countryName: "San Marino", dialCode: "+378" },
  {
    id: "st",
    countryName: "São Tomé and Príncipe (São Tomé e Príncipe)",
    dialCode: "+239",
  },
  {
    id: "sa",
    countryName: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    dialCode: "+966",
  },
  { id: "sn", countryName: "Senegal (Sénégal)", dialCode: "+221" },
  { id: "rs", countryName: "Serbia (Србија)", dialCode: "+381" },
  { id: "sc", countryName: "Seychelles", dialCode: "+248" },
  { id: "sl", countryName: "Sierra Leone", dialCode: "+232" },
  { id: "sg", countryName: "Singapore", dialCode: "+65" },
  { id: "sx", countryName: "Sint Maarten", dialCode: "+1721" },
  { id: "sk", countryName: "Slovakia (Slovensko)", dialCode: "+421" },
  { id: "si", countryName: "Slovenia (Slovenija)", dialCode: "+386" },
  { id: "sb", countryName: "Solomon Islands", dialCode: "+677" },
  { id: "so", countryName: "Somalia (Soomaaliya)", dialCode: "+252" },
  { id: "za", countryName: "South Africa", dialCode: "+27" },
  { id: "kr", countryName: "South Korea (대한민국)", dialCode: "+82" },
  { id: "ss", countryName: "South Sudan (‫جنوب السودان‬‎)", dialCode: "+211" },
  { id: "es", countryName: "Spain (España)", dialCode: "+34" },
  { id: "lk", countryName: "Sri Lanka (ශ්‍රී ලංකාව)", dialCode: "+94" },
  { id: "sd", countryName: "Sudan (‫السودان‬‎)", dialCode: "+249" },
  { id: "sr", countryName: "Suriname", dialCode: "+597" },
  { id: "sj", countryName: "Svalbard and Jan Mayen", dialCode: "+47" },
  { id: "sz", countryName: "Swaziland", dialCode: "+268" },
  { id: "se", countryName: "Sweden (Sverige)", dialCode: "+46" },
  { id: "ch", countryName: "Switzerland (Schweiz)", dialCode: "+41" },
  { id: "sy", countryName: "Syria (‫سوريا‬‎)", dialCode: "+963" },
  { id: "tw", countryName: "Taiwan (台灣)", dialCode: "+886" },
  { id: "tj", countryName: "Tajikistan", dialCode: "+992" },
  { id: "tz", countryName: "Tanzania", dialCode: "+255" },
  { id: "th", countryName: "Thailand (ไทย)", dialCode: "+66" },
  { id: "tl", countryName: "Timor-Leste", dialCode: "+670" },
  { id: "tg", countryName: "Togo", dialCode: "+228" },
  { id: "tk", countryName: "Tokelau", dialCode: "+690" },
  { id: "to", countryName: "Tonga", dialCode: "+676" },
  { id: "tt", countryName: "Trinisoad and Tobago", dialCode: "+1868" },
  { id: "tn", countryName: "Tunisia (‫تونس‬‎)", dialCode: "+216" },
  { id: "tr", countryName: "Turkey (Türkiye)", dialCode: "+90" },
  { id: "tm", countryName: "Turkmenistan", dialCode: "+993" },
  { id: "tc", countryName: "Turks and Caicos Islands", dialCode: "+1649" },
  { id: "tv", countryName: "Tuvalu", dialCode: "+688" },
  { id: "vi", countryName: "U.S. Virgin Islands", dialCode: "+1340" },
  { id: "ug", countryName: "Uganda", dialCode: "+256" },
  { id: "ua", countryName: "Ukraine (Україна)", dialCode: "+380" },
  {
    id: "ae",
    countryName: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    dialCode: "+971",
  },
  { id: "gb", countryName: "United Kingdom", dialCode: "+44" },
  { id: "us", countryName: "United States", dialCode: "+1" },
  { id: "uy", countryName: "Uruguay", dialCode: "+598" },
  { id: "uz", countryName: "Uzbekistan (Oʻzbekiston)", dialCode: "+998" },
  { id: "vu", countryName: "Vanuatu", dialCode: "+678" },
  {
    id: "va",
    countryName: "Vatican City (Città del Vaticano)",
    dialCode: "+39",
  },
  { id: "ve", countryName: "Venezuela", dialCode: "+58" },
  { id: "vn", countryName: "Vietnam (Việt Nam)", dialCode: "+84" },
  {
    id: "wf",
    countryName: "Wallis and Futuna (Wallis-et-Futuna)",
    dialCode: "+681",
  },
  { id: "ye", countryName: "Yemen (‫اليمن‬‎)", dialCode: "+967" },
  { id: "zm", countryName: "Zambia", dialCode: "+260" },
  { id: "zw", countryName: "Zimbabwe", dialCode: "+263" },
  { id: "ax", countryName: "Åland Islands", dialCode: "+358" },
] as const
