export const COUNTRIES = [
  { countryName: "Afghanistan (‫افغانستان‬‎)", id: "af", dialCode: "+93" },
  { countryName: "Albania (Shqipëri)", id: "al", dialCode: "+355" },
  { countryName: "Algeria (‫الجزائر‬‎)", id: "dz", dialCode: "+213" },
  { countryName: "American Samoa", id: "as", dialCode: "+1684" },
  { countryName: "Andorra", id: "ad", dialCode: "+376" },
  { countryName: "Angola", id: "ao", dialCode: "+244" },
  { countryName: "Anguilla", id: "ai", dialCode: "+1264" },
  { countryName: "Antigua and Barbuda", id: "ag", dialCode: "+1268" },
  { countryName: "Argentina", id: "ar", dialCode: "+54" },
  { countryName: "Armenia (Հայաստան)", id: "am", dialCode: "+374" },
  { countryName: "Aruba", id: "aw", dialCode: "+297" },
  { countryName: "Australia", id: "au", dialCode: "+61" },
  { countryName: "Austria (Österreich)", id: "at", dialCode: "+43" },
  { countryName: "Azerbaijan (Azərbaycan)", id: "az", dialCode: "+994" },
  { countryName: "Bahamas", id: "bs", dialCode: "+1242" },
  { countryName: "Bahrain (‫البحرين‬‎)", id: "bh", dialCode: "+973" },
  { countryName: "Bangladesh (বাংলাদেশ)", id: "bd", dialCode: "+880" },
  { countryName: "Barbados", id: "bb", dialCode: "+1246" },
  { countryName: "Belarus (Беларусь)", id: "by", dialCode: "+375" },
  { countryName: "Belgium (België)", id: "be", dialCode: "+32" },
  { countryName: "Belize", id: "bz", dialCode: "+501" },
  { countryName: "Benin (Bénin)", id: "bj", dialCode: "+229" },
  { countryName: "Bermuda", id: "bm", dialCode: "+1441" },
  { countryName: "Bhutan (འབྲུག)", id: "bt", dialCode: "+975" },
  { countryName: "Bolivia", id: "bo", dialCode: "+591" },
  {
    countryName: "Bosnia and Herzegovina (Босна и Херцеговина)",
    id: "ba",
    dialCode: "+387",
  },
  { countryName: "Botswana", id: "bw", dialCode: "+267" },
  { countryName: "Brazil (Brasil)", id: "br", dialCode: "+55" },
  { countryName: "British Indian Ocean Territory", id: "io", dialCode: "+246" },
  { countryName: "British Virgin Islands", id: "vg", dialCode: "+1284" },
  { countryName: "Brunei", id: "bn", dialCode: "+673" },
  { countryName: "Bulgaria (България)", id: "bg", dialCode: "+359" },
  { countryName: "Burkina Faso", id: "bf", dialCode: "+226" },
  { countryName: "Burundi (Uburundi)", id: "bi", dialCode: "+257" },
  { countryName: "Cambodia (កម្ពុជា)", id: "kh", dialCode: "+855" },
  { countryName: "Cameroon (Cameroun)", id: "cm", dialCode: "+237" },
  { countryName: "Canada", id: "ca", dialCode: "+1" },
  { countryName: "Cape Verde (Kabu Verdi)", id: "cv", dialCode: "+238" },
  { countryName: "Cayman Islands", id: "ky", dialCode: "+1345" },
  {
    countryName: "Central African Republic (République centrafricaine)",
    id: "cf",
    dialCode: "+236",
  },
  { countryName: "Chad (Tchad)", id: "td", dialCode: "+235" },
  { countryName: "Chile", id: "cl", dialCode: "+56" },
  { countryName: "China (中国)", id: "cn", dialCode: "+86" },
  { countryName: "Christmas Island", id: "cx", dialCode: "+61" },
  { countryName: "Cocos (Keeling) Islands", id: "cc", dialCode: "+61" },
  { countryName: "Colombia", id: "co", dialCode: "+57" },
  { countryName: "Comoros (‫جزر القمر‬‎)", id: "km", dialCode: "+269" },
  {
    countryName: "Congo (DRC) (Jamhuri ya Kisoemokrasia ya Kongo)",
    id: "cd",
    dialCode: "+243",
  },
  {
    countryName: "Congo (Republic) (Congo-Brazzaville)",
    id: "cg",
    dialCode: "+242",
  },
  { countryName: "Cook Islands", id: "ck", dialCode: "+682" },
  { countryName: "Costa Rica", id: "cr", dialCode: "+506" },
  { countryName: "Côte d’Ivoire", id: "ci", dialCode: "+225" },
  { countryName: "Croatia (Hrvatska)", id: "hr", dialCode: "+385" },
  { countryName: "Cuba", id: "cu", dialCode: "+53" },
  { countryName: "Curaçao", id: "cw", dialCode: "+599" },
  { countryName: "Cyprus (Κύπρος)", id: "cy", dialCode: "+357" },
  {
    countryName: "Czech Republic (Česká republika)",
    id: "cz",
    dialCode: "+420",
  },
  { countryName: "Denmark (Danmark)", id: "dk", dialCode: "+45" },
  { countryName: "Djibouti", id: "dj", dialCode: "+253" },
  { countryName: "Dominica", id: "dm", dialCode: "+1767" },
  {
    countryName: "Dominican Republic (República Dominicana)",
    id: "do",
    dialCode: "+1",
  },
  { countryName: "Ecuador", id: "ec", dialCode: "+593" },
  { countryName: "Egypt (‫مصر‬‎)", id: "eg", dialCode: "+20" },
  { countryName: "El Salvador", id: "sv", dialCode: "+503" },
  {
    countryName: "Equatorial Guinea (Guinea Ecuatorial)",
    id: "gq",
    dialCode: "+240",
  },
  { countryName: "Eritrea", id: "er", dialCode: "+291" },
  { countryName: "Estonia (Eesti)", id: "ee", dialCode: "+372" },
  { countryName: "Ethiopia", id: "et", dialCode: "+251" },
  {
    countryName: "Falkland Islands (Islas Malvinas)",
    id: "fk",
    dialCode: "+500",
  },
  { countryName: "Faroe Islands (Føroyar)", id: "fo", dialCode: "+298" },
  { countryName: "Fiji", id: "fj", dialCode: "+679" },
  { countryName: "Finland (Suomi)", id: "fi", dialCode: "+358" },
  { countryName: "France", id: "fr", dialCode: "+33" },
  {
    countryName: "French Guiana (Guyane française)",
    id: "gf",
    dialCode: "+594",
  },
  {
    countryName: "French Polynesia (Polynésie française)",
    id: "pf",
    dialCode: "+689",
  },
  { countryName: "Gabon", id: "ga", dialCode: "+241" },
  { countryName: "Gambia", id: "gm", dialCode: "+220" },
  { countryName: "Georgia (საქართველო)", id: "ge", dialCode: "+995" },
  { countryName: "Germany (Deutschland)", id: "de", dialCode: "+49" },
  { countryName: "Ghana (Gaana)", id: "gh", dialCode: "+233" },
  { countryName: "Gibraltar", id: "gi", dialCode: "+350" },
  { countryName: "Greece (Ελλάδα)", id: "gr", dialCode: "+30" },
  { countryName: "Greenland (Kalaallit Nunaat)", id: "gl", dialCode: "+299" },
  { countryName: "Grenada", id: "gd", dialCode: "+1473" },
  { countryName: "Guadeloupe", id: "gp", dialCode: "+590" },
  { countryName: "Guam", id: "gu", dialCode: "+1671" },
  { countryName: "Guatemala", id: "gt", dialCode: "+502" },
  { countryName: "Guernsey", id: "gg", dialCode: "+44" },
  { countryName: "Guinea (Guinée)", id: "gn", dialCode: "+224" },
  { countryName: "Guinea-Bissau (Guiné Bissau)", id: "gw", dialCode: "+245" },
  { countryName: "Guyana", id: "gy", dialCode: "+592" },
  { countryName: "Haiti", id: "ht", dialCode: "+509" },
  { countryName: "Honduras", id: "hn", dialCode: "+504" },
  { countryName: "Hong Kong (香港)", id: "hk", dialCode: "+852" },
  { countryName: "Hungary (Magyarország)", id: "hu", dialCode: "+36" },
  { countryName: "Iceland (Ísland)", id: "is", dialCode: "+354" },
  { countryName: "India (भारत)", id: "in", dialCode: "+91" },
  { countryName: "Indonesia", id: "id", dialCode: "+62" },
  { countryName: "Iran (‫ایران‬‎)", id: "ir", dialCode: "+98" },
  { countryName: "Iraq (‫العراق‬‎)", id: "iq", dialCode: "+964" },
  { countryName: "Ireland", id: "ie", dialCode: "+353" },
  { countryName: "Isle of Man", id: "im", dialCode: "+44" },
  { countryName: "Israel (‫ישראל‬‎)", id: "il", dialCode: "+972" },
  { countryName: "Italy (Italia)", id: "it", dialCode: "+39" },
  { countryName: "Jamaica", id: "jm", dialCode: "+1" },
  { countryName: "Japan (日本)", id: "jp", dialCode: "+81" },
  { countryName: "Jersey", id: "je", dialCode: "+44" },
  { countryName: "Jordan (‫الأردن‬‎)", id: "jo", dialCode: "+962" },
  { countryName: "Kazakhstan (Казахстан)", id: "kz", dialCode: "+7" },
  { countryName: "Kenya", id: "ke", dialCode: "+254" },
  { countryName: "Kiribati", id: "ki", dialCode: "+686" },
  { countryName: "Kosovo", id: "xk", dialCode: "+383" },
  { countryName: "Kuwait (‫الكويت‬‎)", id: "kw", dialCode: "+965" },
  { countryName: "Kyrgyzstan (Кыргызстан)", id: "kg", dialCode: "+996" },
  { countryName: "Laos (ລາວ)", id: "la", dialCode: "+856" },
  { countryName: "Latvia (Latvija)", id: "lv", dialCode: "+371" },
  { countryName: "Lebanon (‫لبنان‬‎)", id: "lb", dialCode: "+961" },
  { countryName: "Lesotho", id: "ls", dialCode: "+266" },
  { countryName: "Liberia", id: "lr", dialCode: "+231" },
  { countryName: "Libya (‫ليبيا‬‎)", id: "ly", dialCode: "+218" },
  { countryName: "Liechtenstein", id: "li", dialCode: "+423" },
  { countryName: "Lithuania (Lietuva)", id: "lt", dialCode: "+370" },
  { countryName: "Luxembourg", id: "lu", dialCode: "+352" },
  { countryName: "Macau (澳門)", id: "mo", dialCode: "+853" },
  {
    countryName: "North Macedonia (FYROM) (Македонија)",
    id: "mk",
    dialCode: "+389",
  },
  { countryName: "Madagascar (Madagasikara)", id: "mg", dialCode: "+261" },
  { countryName: "Malawi", id: "mw", dialCode: "+265" },
  { countryName: "Malaysia", id: "my", dialCode: "+60" },
  { countryName: "Maldives", id: "mv", dialCode: "+960" },
  { countryName: "Mali", id: "ml", dialCode: "+223" },
  { countryName: "Malta", id: "mt", dialCode: "+356" },
  { countryName: "Marshall Islands", id: "mh", dialCode: "+692" },
  { countryName: "Martinique", id: "mq", dialCode: "+596" },
  { countryName: "Mauritania (‫موريتانيا‬‎)", id: "mr", dialCode: "+222" },
  { countryName: "Mauritius (Moris)", id: "mu", dialCode: "+230" },
  { countryName: "Mayotte", id: "yt", dialCode: "+262" },
  { countryName: "Mexico (México)", id: "mx", dialCode: "+52" },
  { countryName: "Micronesia", id: "fm", dialCode: "+691" },
  { countryName: "Moldova (Republica Moldova)", id: "md", dialCode: "+373" },
  { countryName: "Monaco", id: "mc", dialCode: "+377" },
  { countryName: "Mongolia (Монгол)", id: "mn", dialCode: "+976" },
  { countryName: "Montenegro (Crna Gora)", id: "me", dialCode: "+382" },
  { countryName: "Montserrat", id: "ms", dialCode: "+1664" },
  { countryName: "Morocco (‫المغرب‬‎)", id: "ma", dialCode: "+212" },
  { countryName: "Mozambique (Moçambique)", id: "mz", dialCode: "+258" },
  { countryName: "Myanmar (Burma) (မြန်မာ)", id: "mm", dialCode: "+95" },
  { countryName: "Namibia (Namibië)", id: "na", dialCode: "+264" },
  { countryName: "Nauru", id: "nr", dialCode: "+674" },
  { countryName: "Nepal (नेपाल)", id: "np", dialCode: "+977" },
  { countryName: "Netherlands (Nederland)", id: "nl", dialCode: "+31" },
  {
    countryName: "New Caledonia (Nouvelle-Calédonie)",
    id: "nc",
    dialCode: "+687",
  },
  { countryName: "New Zealand", id: "nz", dialCode: "+64" },
  { countryName: "Nicaragua", id: "ni", dialCode: "+505" },
  { countryName: "Niger (Nijar)", id: "ne", dialCode: "+227" },
  { countryName: "Nigeria", id: "ng", dialCode: "+234" },
  { countryName: "Niue", id: "nu", dialCode: "+683" },
  { countryName: "Norfolk Island", id: "nf", dialCode: "+672" },
  {
    countryName: "North Korea (조선 민주주의 인민 공화국)",
    id: "kp",
    dialCode: "+850",
  },
  { countryName: "Northern Mariana Islands", id: "mp", dialCode: "+1670" },
  { countryName: "Norway (Norge)", id: "no", dialCode: "+47" },
  { countryName: "Oman (‫عُمان‬‎)", id: "om", dialCode: "+968" },
  { countryName: "Pakistan (‫پاکستان‬‎)", id: "pk", dialCode: "+92" },
  { countryName: "Palau", id: "pw", dialCode: "+680" },
  { countryName: "Palestine (‫فلسطين‬‎)", id: "ps", dialCode: "+970" },
  { countryName: "Panama (Panamá)", id: "pa", dialCode: "+507" },
  { countryName: "Papua New Guinea", id: "pg", dialCode: "+675" },
  { countryName: "Paraguay", id: "py", dialCode: "+595" },
  { countryName: "Peru (Perú)", id: "pe", dialCode: "+51" },
  { countryName: "Philippines", id: "ph", dialCode: "+63" },
  { countryName: "Poland (Polska)", id: "pl", dialCode: "+48" },
  { countryName: "Portugal", id: "pt", dialCode: "+351" },
  { countryName: "Puerto Rico", id: "pr", dialCode: "+1" },
  { countryName: "Qatar (‫قطر‬‎)", id: "qa", dialCode: "+974" },
  { countryName: "Réunion (La Réunion)", id: "re", dialCode: "+262" },
  { countryName: "Romania (România)", id: "ro", dialCode: "+40" },
  { countryName: "Russia (Россия)", id: "ru", dialCode: "+7" },
  { countryName: "Rwanda", id: "rw", dialCode: "+250" },
  { countryName: "Saint Barthélemy", id: "bl", dialCode: "+590" },
  { countryName: "Saint Helena", id: "sh", dialCode: "+290" },
  { countryName: "Saint Kitts and Nevis", id: "kn", dialCode: "+1869" },
  { countryName: "Saint Lucia", id: "lc", dialCode: "+1758" },
  {
    countryName: "Saint Martin (Saint-Martin (partie française))",
    id: "mf",
    dialCode: "+590",
  },
  {
    countryName: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    id: "pm",
    dialCode: "+508",
  },
  {
    countryName: "Saint Vincent and the Grenadines",
    id: "vc",
    dialCode: "+1784",
  },
  { countryName: "Samoa", id: "ws", dialCode: "+685" },
  { countryName: "San Marino", id: "SM", dialCode: "+378" },
  {
    countryName: "São Tomé and Príncipe (São Tomé e Príncipe)",
    id: "st",
    dialCode: "+239",
  },
  {
    countryName: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    id: "sa",
    dialCode: "+966",
  },
  { countryName: "Senegal (Sénégal)", id: "sn", dialCode: "+221" },
  { countryName: "Serbia (Србија)", id: "rs", dialCode: "+381" },
  { countryName: "Seychelles", id: "sc", dialCode: "+248" },
  { countryName: "Sierra Leone", id: "sl", dialCode: "+232" },
  { countryName: "Singapore", id: "sg", dialCode: "+65" },
  { countryName: "Sint Maarten", id: "sx", dialCode: "+1721" },
  { countryName: "Slovakia (Slovensko)", id: "sk", dialCode: "+421" },
  { countryName: "Slovenia (Slovenija)", id: "si", dialCode: "+386" },
  { countryName: "Solomon Islands", id: "sb", dialCode: "+677" },
  { countryName: "Somalia (Soomaaliya)", id: "so", dialCode: "+252" },
  { countryName: "South Africa", id: "za", dialCode: "+27" },
  { countryName: "South Korea (대한민국)", id: "kr", dialCode: "+82" },
  { countryName: "South Sudan (‫جنوب السودان‬‎)", id: "ss", dialCode: "+211" },
  { countryName: "Spain (España)", id: "es", dialCode: "+34" },
  { countryName: "Sri Lanka (ශ්‍රී ලංකාව)", id: "lk", dialCode: "+94" },
  { countryName: "Sudan (‫السودان‬‎)", id: "sd", dialCode: "+249" },
  { countryName: "Suriname", id: "sr", dialCode: "+597" },
  { countryName: "Svalbard and Jan Mayen", id: "sj", dialCode: "+47" },
  { countryName: "Swaziland", id: "sz", dialCode: "+268" },
  { countryName: "Sweden (Sverige)", id: "se", dialCode: "+46" },
  { countryName: "Switzerland (Schweiz)", id: "ch", dialCode: "+41" },
  { countryName: "Syria (‫سوريا‬‎)", id: "sy", dialCode: "+963" },
  { countryName: "Taiwan (台灣)", id: "tw", dialCode: "+886" },
  { countryName: "Tajikistan", id: "tj", dialCode: "+992" },
  { countryName: "Tanzania", id: "tz", dialCode: "+255" },
  { countryName: "Thailand (ไทย)", id: "th", dialCode: "+66" },
  { countryName: "Timor-Leste", id: "tl", dialCode: "+670" },
  { countryName: "Togo", id: "tg", dialCode: "+228" },
  { countryName: "Tokelau", id: "tk", dialCode: "+690" },
  { countryName: "Tonga", id: "to", dialCode: "+676" },
  { countryName: "Trinisoad and Tobago", id: "tt", dialCode: "+1868" },
  { countryName: "Tunisia (‫تونس‬‎)", id: "tn", dialCode: "+216" },
  { countryName: "Turkey (Türkiye)", id: "tr", dialCode: "+90" },
  { countryName: "Turkmenistan", id: "tm", dialCode: "+993" },
  { countryName: "Turks and Caicos Islands", id: "tc", dialCode: "+1649" },
  { countryName: "Tuvalu", id: "tv", dialCode: "+688" },
  { countryName: "U.S. Virgin Islands", id: "vi", dialCode: "+1340" },
  { countryName: "Uganda", id: "ug", dialCode: "+256" },
  { countryName: "Ukraine (Україна)", id: "ua", dialCode: "+380" },
  {
    countryName: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    id: "ae",
    dialCode: "+971",
  },
  { countryName: "United Kingdom", id: "gb", dialCode: "+44" },
  { countryName: "United States", id: "us", dialCode: "+1" },
  { countryName: "Uruguay", id: "uy", dialCode: "+598" },
  { countryName: "Uzbekistan (Oʻzbekiston)", id: "uz", dialCode: "+998" },
  { countryName: "Vanuatu", id: "vu", dialCode: "+678" },
  {
    countryName: "Vatican City (Città del Vaticano)",
    id: "va",
    dialCode: "+39",
  },
  { countryName: "Venezuela", id: "ve", dialCode: "+58" },
  { countryName: "Vietnam (Việt Nam)", id: "vn", dialCode: "+84" },
  {
    countryName: "Wallis and Futuna (Wallis-et-Futuna)",
    id: "wf",
    dialCode: "+681",
  },
  { countryName: "Yemen (‫اليمن‬‎)", id: "ye", dialCode: "+967" },
  { countryName: "Zambia", id: "zm", dialCode: "+260" },
  { countryName: "Zimbabwe", id: "zw", dialCode: "+263" },
  { countryName: "Åland Islands", id: "ax", dialCode: "+358" },
] as const
